services:
  - type: web
    name: rk-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: FLASK_ENV
        value: development
      - key: PORT
        value: 10000
